export const GET_PRODUCTS = "GET_PRODUCTS";
export const POST_PRODUCT = "POST_PRODUCT";
export const PUT_PRODUCT = "PUT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";

export const GET_SEARCH = "GET_SEARCH";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORY";
export const PUT_CATEGORY = "PUT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_RELATIONS = "GET_RELATIONS";
export const POST_RELATIONS = "POST_RELATIONS";
export const DELETE_RELATIONS = "DELETE_RELATIONS";
export const GET_RELATIONS_BY_ID = "GET_RELATIONS_BY_ID";
export const GET_RELATIONS_CATEGORIES_BY_ID = "GET_RELATIONS_CATEGORIES_BY_ID";

export const GET_USERS = "GET_USERS"
export const POST_USER = "POST_USER";
export const PUT_USER = "PUT_USER";
export const DELETE_USER = "DELETE_USER";
export const SELECT_USER = "SELECT_USER";

export const POST_PRODUCT_TO_CART = "POST_PRODUCT_TO_CART";
export const GET_PRODUCTS_OF_CART = "GET_PRODUCTS_OF_CART";
export const GET_PRODUCTS_OF_USER = "GET_PRODUCTS_OF_USER";
export const PUT_QUANTITY_OF_PRODUCT = "PUT_QUANTITY_OF_PRODUCT";
export const DELETE_CART = "DELETE_CART";
export const POST_CLONE_CART = "POST_CLONE_CART";

export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export const PUT_ORDER_BY_ID = "PUT_ORDER_BY_ID";
export const PUT_QUANTITY_OF_ORDER = "PUT_QUANTITY_OF_ORDER";
export const GET_ORDER_BY_USER_ID = "GET_ORDER_BY_USER_ID";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_PROMOTE = "USER_PROMOTE";
export const GET_ID_FROM_ID = "GET_ID_FROM_ID";
export const PUT_USER_PASSWORD = "PUT_USER_PASSWORD";

export const POST_REVIEW = "POST_REVIEW";
export const GET_REVIEW = "GET_REVIEW";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS"
export const PUT_REVIEW = "PUT_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";

export const GMAIL_VALIDATION = "GMAIL_VALIDATION";

export const SEND_MAIL = "SEND_MAIL";